title: AG Computational Arithmetic Geometry
description: Website of the research group Computational Arithmetic Geometry at IWR, Heidelberg University
email: arithgeo@iwr.uni-heidelberg.de
author: Victor

# GitHub Pages settings
url: "https://Hausplayer31.github.io" # Your GitHub Pages URL
baseurl: "/ag-comp-arith-geom" # The subpath of your site - RE-ENABLING FOR GITHUB PAGES

# Build settings
theme: jekyll-theme-minimal # This should be set by github-pages gem, but good to have

plugins:
  - jekyll-feed
  # - jekyll-seo-tag # github-pages includes this, usually no need to list explicitly

# Define pages order for navigation if needed
# navigation_pages:
#   - index.md
#   - research.md
#   - publications.md
#   - teaching.md
#   - members.md
#   - links.md
#   - contact.md 
#   - interna.md 